name: api_starter_dev

volumes:
  db: {}

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - postgres.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 6

  api:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '8000:8001'
    env_file:
      - postgres.env
      - api.env
    depends_on:
      postgres:
        condition: service_healthy
