volumes:
  api_db: {}

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - api_db:/var/lib/postgresql/data
      - ./collections:/docker-entrypoint-initdb.d/collections
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
      - ./dev.postgres.env

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    image: api_db
    ports:
      - 8000:8000
    env_file:
      - ./dev.postgres.env
      - ./dev.api.env
    depends_on:
      - postgres
