services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5433:5432
    volumes:
      - ./collections:/docker-entrypoint-initdb.d/collections
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
      - ./test.postgres.env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    image: api_db
    ports:
      - 8001:8000
    command: ["deno", "test", "--allow-net", "--allow-env"]
    env_file:
      - ./test.postgres.env
      - ./test.api.env
    depends_on:
      - postgres
