user:
  read:
    id: "user:read"
    description: |
      With this, a user has permission to view other user records.
  write:
    id: "user:write"
    description: |
      Every user has write permission to her own account, but with
      this, a user has permission to edit other user records.
role:
  grant:
    id: "role:x:grant"
    description: |
      For each role x, this gives the user the permission necessary
      to grant that role to herself or others. For example,
      role:admin:grant gives the user the ability to grant the role
      of admin to any user, including herself.
  revoke:
    id: "role:x:revoke"
    description: |
      For each role x, this gives the user the permission necessary
      to revoke that role from herself or others. For example,
      role:admin:revoke gives the user the ability to revoke the role
      of admin from any user, including herself.